anticrm/platform

dev/launch/src/main.ts
packages/app-mission-control/src/components/Credits.vue
packages/app-mission-control/src/components/Plugins.vue
packages/app-mission-control/src/components/SysInfo.vue
packages/app-storybook/.eslintrc.js
packages/app-storybook/babel.config.js
packages/app-storybook/jest.config.js
packages/app-storybook/package.json
packages/app-storybook/src/components/Storybook.vue
packages/app-storybook/src/index.ts
packages/app-storybook/src/plugin.ts
packages/app-storybook/src/shims-vue.d.ts
packages/app-storybook/tsconfig.json
packages/sparkling-controls/src/InlineEdit.vue
packages/sparkling-theme/css/_components.scss
packages/sparkling-theme/css/_globals.scss
packages/sparkling-theme/css/_variables.scss

Until we able to use `Storybook` with Vue3, here is an initial lightweight storybook alternative within platform. Related to #7

Add `Storybook` application and clean `Mission Control`

---

dev/launch/src/main.ts
packages/app-storybook/src/__model__/model.ts
packages/contact/src/__model__/model.ts
packages/contact/src/components/NewContactForm.vue
packages/contact/src/index.ts
packages/platform-business/.eslintrc.js
packages/platform-business/babel.config.js
packages/platform-business/jest.config.js
packages/platform-business/package.json
packages/platform-business/src/__model__/index.ts
packages/platform-business/src/__model__/model.ts
packages/platform-business/src/index.ts
packages/platform-business/tsconfig.json
packages/sparkling-theme/css/_globals.scss

BusinessObject is a base for most business-related objects. Store creation and modification date, as well as author information. And very likely more things TBD later.

Initial `BusinessObject` contribution

---

AUTHORS
packages/app-storybook/src/components/Calendar.vue
packages/app-storybook/src/components/Storybook.vue
packages/app-storybook/src/index.ts
packages/app-storybook/src/plugin.ts
packages/platform-vue/src/components/Calendar.vue
packages/platform-vue/src/components/calendars/CalendarDay.vue
packages/platform-vue/src/components/calendars/MonthCalendar.vue
packages/platform-vue/src/components/calendars/YearCalendar.vue
packages/platform/src/index.ts
packages/sparkling-controls/src/MonthCalendar.vue

Some initial calendar stuff

---

plugins/app-storybook/src/components/Calendar.vue
plugins/sparkling-controls/src/Button.vue
plugins/sparkling-controls/src/MonthCalendar.vue

Simplification for month control

Simplification for month control

---

dev/prod/src/model.json
packages/memdb/package.json
packages/memdb/src/__tests__/indexeddb.test.ts
packages/memdb/src/index.ts
packages/memdb/src/indexeddb.ts
packages/rpc/src/index.ts
plugins/platform-core/package.json
plugins/platform-core/src/__tests__/core.test.ts
plugins/platform-core/src/session.ts
scripts/build.sh
yarn.lock

Initial `IndexedDB` support

---

plugins/platform-core/src/instance.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/session.ts

split `session` and `prototypes`

---

plugins/chunter/src/__model__/model.ts
plugins/chunter/src/index.ts
plugins/chunter/src/internal/ChatInput.vue
plugins/chunter/src/internal/Chunter.vue
plugins/chunter/src/internal/ContentEditable.vue
plugins/chunter/src/internal/Message.vue
plugins/platform-business/src/index.ts

Implement rich input for chunter
Basic buttons:
*bold* - pattern matching.

Implement rich input for chunter

---

packages/sparkling-controls/src/toolbar/Button.vue
packages/sparkling-controls/src/toolbar/Toolbar.vue
packages/sparkling-rich/package.json
packages/sparkling-rich/src/EditorContent.vue
packages/sparkling-rich/src/index.ts
packages/sparkling-rich/src/internal/commands.ts
packages/sparkling-rich/src/internal/input_rules.ts
packages/sparkling-rich/src/internal/keymap.ts
packages/sparkling-rich/src/internal/schema.ts
packages/sparkling-rich/tsconfig.json
packages/workbench/package.json
packages/workbench/src/components/InputControl.vue
packages/workbench/src/components/Workbench.vue
yarn.lock

Rich input control

---

packages/sparkling-rich/src/EditorContent.vue
packages/sparkling-rich/src/index.ts
packages/sparkling-rich/src/internal/keymap.ts
packages/workbench/src/components/CompletionPopup.vue
packages/workbench/src/components/InputControl.vue

Problems: Popup view for completions are not yet finished.

update to rich control popups

---

AUTHORS
packages/platform/src/__tests__/objectid.test.ts
packages/platform/src/__tests__/platform.test.ts
packages/platform/src/platform.ts

Tests covering objectid.ts and platform.ts.

Extend tests

---

packages/sparkling-controls/src/ScrollView.vue
packages/sparkling-rich/src/EditorContent.vue
packages/sparkling-rich/src/index.ts
packages/sparkling-rich/src/internal/schema.ts
packages/workbench/src/components/CompletionPopup.vue
packages/workbench/src/components/InputControl.vue

A bit of refactorings to make a better completions.

Completion improvements

---

packages/chunter/src/plugin.ts
packages/presentation-ui/package.json
packages/presentation-ui/src/components/CompletionPopup.vue
packages/presentation-ui/src/components/ReferenceInput.vue
packages/presentation-ui/src/index.ts
packages/sparkling-rich/src/EditorContent.vue
packages/workbench/src/components/DetailsForm.vue
packages/workbench/src/components/InputControl.vue

Refactor completion popup

---

packages/presentation-ui/src/components/CompletionPopup.vue

Correct completion popup in case of typing, should select first item if filtering list is changed.

Correct completion popup

---

packages/platform-core/src/plugin.ts
packages/sparkling-controls/src/EditBox.vue

make product working again

---

packages/presentation-ui/src/components/ReferenceInput.vue
packages/sparkling-rich/src/EditorContent.vue
packages/workbench/src/components/Perspective.vue
server/server/src/__tests__/server.test.ts

Set min size for input control in case of multilines
Signed-off-by: Andrey Sobolev <haiodo@xored.com>

Set min size for input control

---

packages/sparkling-rich/src/EditorContent.vue

Fix placeholder display

---

.github/workflows/build.yml

run tests on pull requests

---

packages/workbench/src/components/InputControl.vue

Fix add button size

---

packages/chunter-model/src/index.ts
packages/chunter-model/src/model.ts
packages/chunter/src/index.ts
packages/chunter/src/plugin.ts

`Collab` base class for entities with comments

---

.vscode/settings.json
packages/presentation-ui/src/components/ReferenceInput.vue

Default formatter settings for VSCode

Default formatter settings for VSCode

---

packages/platform-core/src/indexeddb.ts
packages/platform/src/indices/title.ts
packages/platform/src/indices/vdoc.ts
packages/platform/src/utils.ts
server/server/src/service.ts

refactor: `TxProcessor` to support pluggable indices

---

.github/workflows/build.yml
packages/chunter-model/src/model.ts
packages/chunter/src/plugin.ts
packages/platform-model/src/dsl.ts
packages/platform-model/src/index.ts
packages/platform-model/src/model.ts
packages/platform/src/__tests__/text.test.ts
packages/platform/src/indices/text.ts
packages/platform/src/text.ts
server/server/src/service.ts

add backlink index

---

packages/chunter/src/plugin.ts
packages/platform-core/src/index.ts
packages/platform-core/src/indexeddb.ts
packages/platform-core/src/plugin.ts
packages/platform-core/src/titles.ts
packages/platform/src/text.ts
packages/workbench/src/components/DetailsForm.vue
packages/workbench/src/components/Spotlight.vue

initial backllinks implementation

---

dev/tool/src/index.ts
packages/chunter-model/src/model.ts
packages/recruitment-model/src/model.ts
packages/task-model/src/model.ts
packages/workbench-model/src/model.ts
packages/workbench/src/components/DetailsForm.vue
packages/workbench/src/components/Workbench.vue
packages/workbench/src/index.ts

clean: application class

---

package.json
yarn.lock

fix package and yarn.lock

---

plugins/platform-ui/src/components/Component.svelte
plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/platform-ui/src/stores.ts

initial modal support

---

packages/core/src/core.ts
packages/core/src/model.ts
packages/core/src/utils.ts
plugins/platform-core/src/cache.ts
plugins/platform-core/src/graph.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/modeldb.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/queries.ts
plugins/platform-core/src/titles.ts
plugins/presentation/src/utils.ts
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/utils.ts
server/server/src/service.ts

new core work in progress

---

packages/platform-core/src/plugin.ts

Add rpc listener to process backend broadcasts.
Issue: #101
Signed-off-by: Roman Kuskov <roman.kuskov@gmail.com>

Fix problem with UI updating on server broadcast event

---

plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/presentation/src/components/internal/Properties.svelte
plugins/presentation/src/index.ts
plugins/presentation/src/plugin.ts
plugins/task/src/__model__.ts
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/index.ts
plugins/task/src/svelte.d.ts
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/CreateSpace.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/index.ts
plugins/workbench/src/plugin.ts
plugins/workbench/src/utils.ts

initial object properties

---

packages/sparkling-controls/src/toolbar/Button.svelte
packages/sparkling-controls/src/toolbar/Toolbar.svelte
plugins/presentation/src/components/refinput/CompletionPopup.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte

Svelte Rich fixes

---

packages/sparkling-controls/src/InlineEdit.svelte
plugins/platform-core/src/__model__.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/presentation/src/components/AttributeEditor.svelte
plugins/presentation/src/components/internal/Properties.svelte
plugins/presentation/src/components/internal/Table.svelte
plugins/presentation/src/components/internal/editors/StringEditor.svelte
plugins/presentation/src/plugin.ts
plugins/presentation/src/utils.ts
plugins/task/src/__model__.ts
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/utils.ts
plugins/workbench/src/components/internal/CreateForm.svelte
yarn.lock

initial create form

---

plugins/chunter/src/components/internal/ActivityView.svelte
plugins/presentation/src/components/internal/Table.svelte
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte

space example

---

dev/tool/src/user.ts
plugins/chunter/src/__model__.ts
plugins/chunter/src/components/internal/ChatMessageItem.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/components/internal/MessageBody.svelte
plugins/chunter/src/components/internal/MessageInfo.svelte
plugins/chunter/src/components/internal/SpaceInfo.svelte
plugins/chunter/src/index.ts
plugins/chunter/src/plugin.ts
plugins/chunter/src/utils.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/workbench/src/__model__.ts
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/index.ts

One chat per space implemented.

Initial support of chats

---

plugins/chunter/src/components/internal/ChatView.svelte

Merge master with re-fixing bug #101 in the new architecture.

Merge master and re-fix bug #101 in the new architecture

---

packages/sparkling-controls/src/ScrollView.svelte
packages/sparkling-rich/src/EditorContent.svelte
plugins/chunter/src/components/internal/ActivityView.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/presentation/src/components/refinput/CompletionPopup.svelte
plugins/workbench/src/components/internal/Application.svelte

* Show scrollbars on main views when content doesn't fit.
* Automatic scrolling down on Chat and Activity views, also in the case when a user enters new messages.
* Enable scrollbars in Completion popup.
* Hide scrollbars if the content fits into the window, also in Linux Chrome.

Add scroll view

---

plugins/platform-ui/src/components/internal/Modal.svelte
plugins/workbench/src/components/internal/Application.svelte

remove object creation form off the bottom

---

packages/sparkling-rich/src/EditorContent.svelte

Signed-off-by: Roman Kuskov <roman.kuskov@gmail.com>

fix bug when input control's content didn't disappear on submit

---

README.md
plugins/guidebook/src/components/internal/PageBlock.svelte

Fix highlight styles

---

packages/sparkling-rich/package.json
packages/sparkling-rich/src/EditorContent.svelte
packages/sparkling-rich/src/index.ts
plugins/guidebook/src/components/Guidebook.svelte
plugins/guidebook/src/components/internal/PageBlock.svelte
plugins/guidebook/src/components/internal/ReferenceInput.svelte
plugins/guidebook/src/components/internal/toolbar.svelte
plugins/presentation/src/components/refinput/CompletionPopup.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte

+ Fix hover message
+ Fix completion
+ formatting
+ minor issue

Fix scroll support for reference input

---

plugins/presentation/src/components/internal/Table.svelte
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte

show object detail in table view

---

plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/presentation/src/components/internal/Table.svelte
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/proxies/MainComponent.svelte

detached detail view

---

plugins/platform-core/src/plugin.ts
plugins/task/src/__model__.ts
plugins/workbench/src/components/internal/Spotlight.svelte
plugins/workbench/src/components/internal/Workbench.svelte

initial spotlight and titles domain

---

plugins/workbench/src/components/internal/Workbench.svelte

Ctrl+S for spotlight

---

plugins/platform-core/src/plugin.ts
plugins/platform-core/src/titles.ts

query title for specific classes

---

plugins/guidebook/src/components/internal/ReferenceInput.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte

Use title search for reference inputs

---

plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/utils.ts
plugins/platform-core/src/plugin.ts
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/utils.ts

backlinks example and more convenient queries

---

packages/core/src/core.ts
packages/core/src/model.ts
packages/core/src/text.ts
packages/model/src/dsl.ts
plugins/chunter/src/__model__.ts
plugins/chunter/src/components/internal/ActivityView.svelte
plugins/chunter/src/components/internal/ChatMessageItem.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/components/internal/MessageInfo.svelte
plugins/chunter/src/index.ts
plugins/platform-core/src/__model__.ts
plugins/platform-core/src/graph.ts
plugins/platform-ui/src/index.ts
plugins/presentation/src/__model__.ts

Only comments for text content

---

packages/core/src/textmodel.ts
packages/sparkling-rich/package.json
packages/sparkling-rich/src/EditorContent.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/index.ts
plugins/chunter/src/plugin.ts
plugins/guidebook/src/components/internal/ReferenceInput.svelte
plugins/presentation/src/components/MessageViewer.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte
plugins/workbench/src/components/internal/InputControl.svelte

Refactor to use message model

---

packages/platform/src/index.ts
plugins/chunter/src/components/internal/Comments.svelte
plugins/chunter/src/components/internal/PageProperties.svelte
plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte
plugins/workbench/src/utils.ts

Comments, RunningPlugins, and CreateForm changes

---

packages/core/src/text.ts
packages/core/src/textmodel.ts
packages/sparkling-rich/src/EditorContent.svelte
plugins/chunter/src/components/internal/ChatMessageItem.svelte
plugins/chunter/src/components/internal/MessageInfo.svelte
plugins/chunter/src/index.ts
plugins/chunter/src/plugin.ts
plugins/presentation/src/components/MessageViewer.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte

Continue refactoring

---

plugins/chunter/src/components/internal/Backlink.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/components/internal/Comment.svelte
plugins/chunter/src/components/internal/Comments.svelte
plugins/platform-ui/src/index.ts

comments and backlinks

---

plugins/platform-core/src/titles.ts

Fix empty title

---

README.md
dev/tool/package.json
dev/tool/src/index.ts
dev/tool/src/init.ts
dev/tool/src/user.ts
packages/core/src/model.ts
server/accounts/src/__tests__/accounts.test.ts
server/accounts/src/index.ts
server/front/src/index.ts
server/server/src/server.ts
server/server/src/service.ts
server/server/src/workspace.ts
server/server/tsconfig.json

+ Allow to create multiple users and login with them.
+ Allow to associate and de/associate workspace to/from user
+ Use one transaction class per workspace.

Fix creating of accounts

---

.github/workflows/build.yml
packages/core/src/__tests__/model.test.ts
packages/core/src/core.ts
packages/core/src/model.ts
packages/core/src/text.ts
packages/core/src/title.ts
packages/core/src/tx.ts
packages/core/src/vdoc.ts
packages/model/src/builder.ts
packages/model/src/dsl.ts
packages/model/tsconfig.json
packages/platform/src/index.ts
plugins/chunter/src/__model__.ts
plugins/chunter/src/components/internal/ActivityItem.svelte
plugins/chunter/src/components/internal/MessageInfo.svelte
plugins/chunter/src/components/internal/PageInfo.svelte
plugins/chunter/src/components/internal/SpaceInfo.svelte
plugins/chunter/src/utils.ts
plugins/contact/src/__model__.ts
plugins/platform-core/src/__model__.ts
plugins/platform-core/src/plugin.ts
plugins/task/src/__model__.ts
plugins/workbench/src/__model__.ts
server/accounts/src/index.ts
server/server/jest.config.js
server/server/package.json
server/server/src/__tests__/server.test.ts
server/server/src/server.ts
server/server/tsconfig.json

#DSL 
* Refactor ModelClass => Class$ in DSL
* Refactor ModelMixin => Mixin$ in DSL
* Refactor Array => ArrayOf$ in DSL
* Refactor InstanceOf => InstanceOf$  in DSL
+ Add of BagOf
+ Add of RefTo
And make them work as chained elements on model.
```
@Class$(core.class.Collab, core.class.VDoc)
class TCollab extends TVDoc implements Collab {
@ArrayOf$()
@InstanceOf$(chunter.class.Comment)
@UX('Комментарии' as IntlString, chunter.icon.Chunter) comments?: Comment[]
}
```
* CreateTx now had AnyLayout as object and _objectClass and _objectId

A bit of DSL updates and related

---

dev/tool/src/index.ts
dev/tool/src/user.ts
packages/core/src/core.ts
packages/core/src/model.ts
packages/core/src/text.ts
packages/core/src/vdoc.ts
plugins/platform-core/src/__model__.ts
plugins/platform-core/src/cache.ts
plugins/platform-core/src/graph.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/queries.ts
plugins/platform-core/src/titles.ts
plugins/platform-core/src/tx.ts
plugins/workbench/src/__model__.ts
server/accounts/jest.config.js
server/accounts/tsconfig.json
server/front/jest.config.js
server/front/tsconfig.json
server/server/src/__tests__/server.test.ts
server/server/src/__tests__/serversuite.ts
server/server/src/__tests__/service.test.ts
server/server/src/index.ts
server/server/src/rpc.ts
server/server/src/server.ts
server/server/src/service.ts
server/server/src/spaces.ts
server/server/src/workspace.ts

+ Control object operations based on space security

Space security

---

packages/core/src/model.ts
plugins/platform-core/src/queries.ts
server/server/src/spaces.ts

Fix push is not working

---

packages/sparkling-theme/src/components/Theme.svelte
packages/sparkling-theme/src/themes.ts
plugins/platform-ui/src/components/internal/ThemeSelector.svelte

add biege theme, change colors, fix widget

---

packages/sparkling-theme/src/components/Theme.svelte
plugins/chunter/src/__meta__.ts
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/components/internal/DateItem.svelte
plugins/chunter/src/index.ts
plugins/workbench/src/components/internal/Finder.svelte
plugins/workbench/src/components/internal/Workbench.svelte

add component dateitem

---

plugins/task/src/components/internal/StatusLabel.svelte
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/components/internal/UserInfo.svelte

add components userinfo and statuslabel

---

plugins/platform-ui/src/components/internal/Modal.svelte
plugins/workbench/src/components/internal/spaces/JoinSpace.svelte

change design component joinspace

---

.idea/runConfigurations/Server.xml
packages/model/src/model.ts
plugins/platform-core/src/queries.ts
plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte
server/server/src/__tests__/service.test.ts
server/server/src/service.ts
server/server/src/spaces.ts
server/server/src/workspace.ts

Fix queries to work with space join/leave

Fix queries to work with space join/leave

---

.gitignore
docs/api-documenter.json
docs/data/packages.yml
packages/platform/api-extractor.json
packages/platform/package.json
packages/platform/tsconfig.json
yarn.lock

add api doc generation

---

plugins/workbench/src/components/internal/spaces/CreateSpace.svelte
server/server/src/__tests__/service.test.ts
server/server/src/spaces.ts

Fix space creation dialog

---

packages/core/src/__model__.ts
packages/core/src/space.ts
plugins/presentation/src/plugin.ts
plugins/workbench/src/__model__.ts
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/Workbench.svelte
plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte
plugins/workbench/src/components/internal/spaces/SpaceItem.svelte
plugins/workbench/src/components/internal/spaces/utils.ts

- - remove autoJoin field for Space
- + add archived state for space, and hide archived spaces.

Add support of archived spaces

---

.gitignore
docs/themes/thxvscode/layouts/partials/navbarSticky.html

push build

---

.github/workflows/build.yml
docs/config.yml
docs/themes/thxvscode/layouts/_default/_markup/render-link.html
docs/themes/thxvscode/layouts/apis/list.html
docs/themes/thxvscode/layouts/partials/menu.html
docs/themes/thxvscode/layouts/partials/navbarSticky.html
package.json

add `build` step, correct `test` step

---

packages/sparkling-controls/src/CheckBox.svelte
packages/sparkling-controls/src/InlineEdit.svelte
packages/sparkling-controls/src/toolbar/Button.svelte
packages/sparkling-theme/src/components/Theme.svelte
packages/sparkling-theme/src/themes.ts
plugins/chunter/src/components/internal/ActivityItem.svelte
plugins/chunter/src/components/internal/Comment.svelte
plugins/platform-ui/src/components/IconButton.svelte
plugins/platform-ui/src/components/internal/ThemeSelector.svelte
plugins/presentation/src/components/refinput/CompletionPopup.svelte
plugins/task/src/components/internal/UserInfo.svelte
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/SpaceItem.svelte
plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte
plugins/workbench/src/components/internal/spaces/CreateSpace.svelte
plugins/workbench/src/components/internal/spaces/SpaceItem.svelte

redesign new task, add color, change styles for buttons

---

packages/sparkling-controls/src/InlineEdit.svelte
plugins/workbench/src/components/internal/CreateForm.svelte

kill style prop

---

docs/data/packages.yml
package.json
packages/core/api-extractor.json
packages/core/package.json
packages/core/src/index.ts
packages/model/api-extractor.json
packages/model/package.json
packages/model/tsconfig.json

add api documentation for `core` and `model` packages

---

packages/core/src/text.ts
packages/core/src/title.ts
packages/core/src/tx.ts
packages/core/src/utils.ts
packages/core/src/vdoc.ts
packages/model/src/tx.ts

rename `Index` to `DomainIndex`

---

.eslintrc.js
.idea/inspectionProfiles/Project_Default.xml
README.md
docs/content/docs/concepts/code-structure.md
docs/data/packages.yml
package.json
packages/foundation/api-extractor.json
packages/foundation/babel.config.js
packages/foundation/jest.config.js
packages/foundation/package.json
packages/foundation/src/index.ts
packages/foundation/tsconfig.json
packages/platform/src/index.ts

* introduce `foundation` package
* wip fixing dependencies
* document dependencies

introduce 'foundation' package

---

.eslintrc.js
packages/core/src/classes.ts
packages/core/src/rpc.ts
packages/core/src/space.ts

optimize imports, make linter happy

---

packages/sparkling-controls/src/EditBox.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/spaces/AddUser.svelte
plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte
plugins/workbench/src/components/internal/spaces/CreateSpace.svelte
plugins/workbench/src/components/internal/spaces/JoinSpace.svelte
plugins/workbench/src/components/internal/spaces/SpaceItem.svelte
plugins/workbench/src/components/internal/spaces/SpaceOptions.svelte

* user inner styles for some of space components
* Space Creation in middle screen popup

Space UI cleanups

---

docs/content/docs/concepts/code-structure.md
packages/core/src/__model__.ts
packages/core/src/index.ts
packages/core/src/model.ts
packages/core/src/text.ts
packages/core/src/title.ts
packages/core/src/tx.ts
packages/core/src/vdoc.ts
packages/model/src/__model__.ts
packages/model/src/__tests__/model.test.ts
packages/model/src/__tests__/test_tasks.ts
packages/model/src/builder.ts
packages/model/src/dsl.ts
packages/model/src/index.ts
plugins/platform-core/src/modeldb.ts
plugins/platform-core/src/operations.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/queries.ts
plugins/platform-core/src/tx.ts
plugins/presentation/src/__model__.ts
plugins/workbench/src/__model__.ts
server/server/src/mongo_utils.ts
server/server/src/workspace.ts

move 'model' from 'model' to 'core'

---

docs/content/docs/concepts/code-structure.md
docs/data/packages.yml
packages/core/src/__tests__/textmodel.test.ts
packages/core/src/index.ts
packages/core/src/indices/text.ts
packages/text/api-extractor.json
packages/text/babel.config.js
packages/text/jest.config.js
packages/text/package.json
packages/text/src/index.ts
packages/text/tsconfig.json
plugins/chunter/src/components/internal/Comment.svelte
plugins/chunter/src/components/internal/MessageInfo.svelte
plugins/chunter/src/index.ts
plugins/chunter/src/plugin.ts
plugins/presentation/src/components/MessageViewer.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte

introduce 'text' package

---

plugins/workbench/src/components/internal/spaces/SpaceItem.svelte

fix and clean SpaceItem

---

packages/core/src/classes.ts
packages/model/src/index.ts

add proper ids to 'model'

---

packages/sparkling-controls/src/CheckBox.svelte

fix component checkbox

---

.idea/codeStyles/Project.xml

Use double quotes for svelte html

---

.idea/codeStyles/Project.xml
packages/core/src/classes.ts
packages/core/src/model.ts
packages/model/src/dsl.ts
packages/model/src/models/core.ts
plugins/chunter/src/__model__.ts
plugins/contact/src/__model__.ts
plugins/contact/src/plugin.ts
plugins/platform-ui/src/components/Component.svelte
plugins/presentation/src/__model__.ts
plugins/presentation/src/index.ts
plugins/presentation/src/plugin.ts
plugins/task/src/__meta__.ts
plugins/task/src/__model__.ts
plugins/task/src/components/internal/CreateForm.svelte
plugins/task/src/components/internal/StatusLabel.svelte
plugins/task/src/components/internal/TaskInfo.svelte
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/index.ts
plugins/task/src/plugin.ts
plugins/task/src/utils.ts
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/proxies/MainComponent.svelte
plugins/workbench/src/utils.ts
server/server/package.json
yarn.lock

Tasks rework

---

plugins/chunter/src/components/Comments.svelte
plugins/chunter/src/components/internal/Backlink.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/chunter/src/components/internal/PageProperties.svelte
plugins/guidebook/src/components/internal/ReferenceInput.svelte
plugins/login/src/plugin.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/operations.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/queries.ts
plugins/platform-ui/src/components/ActionBar.svelte
plugins/platform-ui/src/components/ComboBox.svelte
plugins/platform-ui/src/components/Component.svelte
plugins/platform-ui/src/components/actions.ts
plugins/platform-ui/src/components/internal/Modal.svelte
plugins/presentation/src/components/internal/Table.svelte
plugins/presentation/src/components/refinput/ReferenceInput.svelte
plugins/presentation/src/index.ts
plugins/presentation/src/plugin.ts
plugins/task/src/__model__.ts
plugins/task/src/components/internal/NewTaskForm.svelte
plugins/task/src/components/internal/StatusLabel.svelte
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/index.ts
plugins/task/src/plugin.ts
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte
plugins/workbench/src/utils.ts

Tasks rework part2

---

packages/core/src/model.ts
packages/model/src/__model__.ts
plugins/chunter/src/__meta__.ts
plugins/chunter/src/__model__.ts
plugins/chunter/src/components/Comments.svelte
plugins/chunter/src/components/internal/ActivityView.svelte
plugins/chunter/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/platform-ui/src/components/Component.svelte
plugins/presentation/src/__meta__.ts
plugins/presentation/src/__model__.ts
plugins/presentation/src/components/internal/TablePresenter.svelte
plugins/presentation/src/index.ts
plugins/presentation/src/plugin.ts
plugins/task/src/__model__.ts
plugins/task/src/components/internal/TaskCardPresenter.svelte
plugins/task/src/index.ts
plugins/task/src/plugin.ts
plugins/workbench/src/__model__.ts
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte
plugins/workbench/src/components/internal/PresenterItem.svelte
plugins/workbench/src/components/internal/Workbench.svelte
plugins/workbench/src/components/internal/spaces/SpaceItem.svelte
plugins/workbench/src/index.ts
plugins/workbench/src/utils.ts
server/server/src/workspace.ts

1. Refactor workbench layout. 
2. Define initial class presenters

1. Refactor workbench layout. 2. Define initial class presenters

---

.idea/codeStyles/Project.xml
packages/core/src/model.ts
packages/model/tsconfig.json

remove 'object literal wrap' formatter settings, tweak tsconfig

---

plugins/task/src/components/internal/TaskCard.svelte
plugins/task/src/components/internal/TaskCardPresenter.svelte
plugins/task/src/components/internal/pannable.ts

design kanban for tasks

---

dev/storybook/.storybook/webpack.config.js
dev/storybook/src/stories/Button.stories.js
dev/storybook/src/stories/ThemeDecorator.svelte

storybook theme decorator

---

plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte

change design browsespace

---

AUTHORS
README.md
packages/core/src/__tests__/model.test.ts

Core code coverage improvements: model tests:pass and fail findOne and removeDocument

Core tests

---

plugins/presentation/src/components/internal/Table.svelte

design Table

---

packages/platform/src/index.ts
plugins/login/src/components/LoginForm.svelte
plugins/login/src/index.ts
plugins/login/src/plugin.ts
plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts

Auto select login app if no credentials, and go to app if they are

---

dev/storybook/src/stories/Button.stories.js
dev/storybook/src/stories/Button.svelte
dev/storybook/src/stories/ThemeDecorator.svelte
packages/sparkling-controls/src/Button.svelte

fix comp Button in StoryBook

---

plugins/chunter/src/components/Comments.svelte
plugins/guidebook/src/components/Guidebook.svelte
plugins/login/src/plugin.ts
plugins/platform-ui/src/components/LinkTo.svelte
plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/location.ts
plugins/platform-ui/src/plugin.ts
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte
plugins/workbench/src/components/internal/SpaceItem.svelte
plugins/workbench/src/components/internal/Workbench.svelte
plugins/workbench/src/components/internal/spaces/SpaceItem.svelte

1. Easy access to location with subscribe
2. Encode and parse of URI into path/query and fragment.
3. Update app to use new location schema

A bit more complex routing

---

plugins/workbench/src/components/internal/Spotlight.svelte

A quick fix for spotlight

---

.github/workflows/build.yml
.yamllint
docs/config.yml
docs/data/packages.yml

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
This PR:
1. adds check for YAML files: https://github.com/adrienverge/yamllint
2. fixes found issues by yamllint.

Add yaml-lint check step on ci

---

packages/sparkling-controls/src/Splitter.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte

add comp Splitter in sparkling-control, insert into DefaultPerspective

---

dev/prod/.env
dev/prod/src/main.ts
packages/foundation/src/index.ts
packages/platform/src/index.ts
plugins/contact/src/plugin.ts
plugins/login/src/components/LoginForm.svelte
plugins/login/src/index.ts
plugins/login/src/plugin.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/rpc.ts
plugins/platform-ui/src/components/Component.svelte
plugins/platform-ui/src/components/internal/Root.svelte
plugins/presentation/src/components/internal/Table.svelte
plugins/workbench/src/index.ts
server/accounts/src/index.ts
server/accounts/src/token.ts
server/front/src/index.ts
server/server/src/__tests__/server.test.ts
server/server/src/server.ts
server/server/src/workspace.ts

Fixes #240
1. Authentication page is not auto forward but show info if user is already authenticated.
2. Allow to Logout from Login page if already log-in.
3. Fix plugin re-loading if first attempt caused some exception, un authenticated case for example.
4. Some cleanups

Allow to login and logout

---

AUTHORS
server/server/src/server.ts

When error occurs in the `websocket.on` method no response is sent to the client and the socket is not closed, 
These changes should fix the bug https://github.com/anticrm/platform/issues/254 .

Fix hanging websocket connections

---

plugins/login/src/components/LoginForm.svelte
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte

Fix compile and imports

---

packages/model/package.json
packages/model/src/utils.ts

Add eslint for packages/model project

---

packages/domains/package.json
packages/foundation/package.json
packages/platform/package.json
packages/platform/src/__tests__/platform.test.ts
packages/platform/src/__tests__/plugin1.ts
packages/platform/src/__tests__/plugin2.ts
packages/rpc/package.json

Signed-off-by: Artyom Savchenko artem.savchenko@xored.com

Add eslint for domains, foundation, platform and rpc

---

dev/boot/src/platform.ts
packages/platform/src/index.ts
plugins/chunter/src/__model__.ts
plugins/chunter/src/components/internal/ChatView.svelte
plugins/guidebook/src/components/Guidebook.svelte
plugins/login/src/__meta__.ts
plugins/login/src/plugin.ts
plugins/platform-ui/jest.config.js
plugins/platform-ui/src/__test__/routers.test.ts
plugins/platform-ui/src/components/Component.svelte
plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/location.ts
plugins/platform-ui/src/plugin.ts
plugins/platform-ui/src/routes.ts
plugins/platform-ui/tsconfig.json
plugins/presentation/src/components/internal/Table.svelte
plugins/presentation/src/components/internal/presenters/class/TablePresenter.svelte
plugins/task/src/__model__.ts
plugins/workbench/src/__meta__.ts
plugins/workbench/src/__model__.ts
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/Workbench.svelte
plugins/workbench/src/components/proxies/MainComponent.svelte
plugins/workbench/src/index.ts

1. A context based route matcher
2. Update current components to use new router.
3. Documentation is pending.
Usage of router:
```typescript
interface WorkbenchRouteInfo {
space: string // A ref of space name
app: Ref<WorkbenchApplication>
_class?: Ref<Class<Doc>>
_id?: Ref<Doc>
}
function routeDefaults (): WorkbenchRouteInfo {
return {
space: spaces.length > 0 ? spaces[0].name : '#undefined',
app: applications.length > 0 ? applications[0].route : '#undefined' as Ref<WorkbenchApplication>
} as WorkbenchRouteInfo
}
const router = newRouter<WorkbenchRouteInfo>(':space/:app?_class#_id', (info) => {
if (spaces.length > 0) {
space = spaces.find((s) => (s._id === info.space as Ref<Space>) || s.spaceKey === info.space) || spaces[0]
}
if (applications.length > 0) {
application = …
```

Routes simplification

---

plugins/chunter/src/components/internal/ChatView.svelte
plugins/platform-core/src/plugin.ts
plugins/platform-ui/src/components/Component.svelte
plugins/platform-ui/src/components/internal/Root.svelte
plugins/presentation/src/components/internal/presenters/value/RefPresenter.svelte
plugins/presentation/src/plugin.ts
plugins/workbench/src/components/internal/DefaultPerspective.svelte

Fix chat and some cleanups

---

plugins/chunter/package.json
plugins/chunter/src/__meta__.ts
plugins/chunter/src/plugin.ts
plugins/contact/package.json
plugins/guidebook/package.json
plugins/guidebook/src/plugin.ts
plugins/guidebook/src/registry.ts
plugins/guidebook/src/svelte.d.ts
plugins/login/package.json
plugins/login/src/svelte.d.ts
plugins/platform-i18n/package.json
plugins/platform-ui/package.json
plugins/platform-ui/src/__meta__/meta.ts
plugins/platform-ui/src/stores.ts
plugins/platform-ui/src/svelte.d.ts
plugins/presentation/package.json
plugins/presentation/src/__meta__.ts
plugins/presentation/src/utils.ts
plugins/task/package.json
plugins/task/src/__meta__.ts
plugins/task/src/components/internal/pannable.ts
plugins/task/src/svelte.d.ts
plugins/task/src/utils.ts
plugins/workbench/package.json
plugins/workbench/src/index.ts
plugins/workbench/src/plugin.ts
plugins/workbench/src/svelte.d.ts

Add eslint for plugins and fix lint errors

---

.github/workflows/build.yml
.yamllint

Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
This PR:
1. Updates versions of node action.
2. Makes ci triggerable only on the master branch.
3. A little bit improves time of CI for ubuntu (~30s)
4. Fixes issue with yamllinter

Update ci checks and reduce build/test time

---

plugins/workbench/src/components/internal/Application.svelte

Fix viewlet svelte update

---

plugins/chunter/src/components/Comments.svelte
plugins/chunter/src/components/internal/Comment.svelte
plugins/login/src/components/LoginForm.svelte
plugins/platform-ui/src/components/Component.svelte
plugins/workbench/src/components/internal/ObjectForm.svelte
plugins/workbench/src/components/internal/Workbench.svelte

Fix component flashing and jumping

Fix component flashing and jumping

---

README.md
docs/content/docs/concepts/code-structure.md

Minor documentation updates

---

plugins/chunter/src/components/Comments.svelte
plugins/chunter/src/components/internal/ActivityView.svelte
plugins/chunter/src/components/internal/Backlink.svelte
plugins/chunter/src/components/internal/ChatView.svelte
plugins/platform-ui/src/index.ts
plugins/task/src/components/internal/presenters/StatusPresenter.svelte

Remove `platform-ui` dependency on `platform-core`

---

.gitignore
README.md
dev/boot/src/platform.ts
plugins/login/src/__meta__.ts
plugins/login/src/index.ts
plugins/login/src/plugin.ts
plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/platform-ui/src/routes.ts
plugins/workbench/src/__meta__.ts
plugins/workbench/src/index.ts

1. Allow to define multiple application entry points
2. Fix authentication application selection on / URI.

Allow to define multiple application entry points

---

plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/presentation/src/components/MessageViewer.svelte
plugins/presentation/src/components/internal/presenters/value/RefPresenter.svelte
plugins/presentation/src/index.ts
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/index.ts

Remove `platform-ui` dependency on `@anticrm/core`

---

plugins/presentation/src/__model__.ts
plugins/presentation/src/components/internal/presenters/value/ArrayPresenter.svelte
plugins/presentation/src/index.ts
plugins/presentation/src/plugin.ts

Add array presenter

---

docs/content/docs/advanced/routing.md
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/platform-ui/src/routes.ts
plugins/workbench/src/components/internal/DefaultPerspective.svelte

Some basic routing docs

---

.eslintrc.js
packages/sparkling-rich/package.json
plugins/chunter/package.json
plugins/guidebook/package.json
plugins/login/package.json
plugins/platform-ui/package.json
plugins/presentation/package.json
plugins/task/package.json
plugins/workbench/package.json
yarn.lock

Added basic eslint configuration to work with svelte files(https://github.com/anticrm/platform/issues/262).

Configure eslint for svelte files

---

packages/domains/src/index.ts
packages/model/src/__model__.ts
plugins/chunter/src/__model__.ts
plugins/platform-ui/src/components/LinkTo.svelte
plugins/task/src/__model__.ts
plugins/workbench/src/__model__.ts
plugins/workbench/src/components/internal/ApplicationDashboard.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/spaces/CreateSpace.svelte
plugins/workbench/src/index.ts
plugins/workbench/src/plugin.ts

Initial fix for #285

---

README.md

I hope someday that helps somebody to avoid such issues :sweat_smile: 
Signed-off-by: Ilya Sumbatyants <ilya.sumb@gmail.com>

Restrict docker expose parameter in README

---

plugins/workbench/src/components/internal/Application.svelte

Viewlet should not use routing

---

plugins/platform-ui/package.json
plugins/platform-ui/src/routes.ts
plugins/presentation/package.json
plugins/presentation/src/utils.ts
plugins/presentation/tsconfig.json
yarn.lock

Prevent router extra refresh operations

Prevent router extra refresh operations

---

dev/boot/package.json
dev/boot/src/index.ts
dev/prod/package.json
dev/prod/src/main.ts
dev/prod/src/svelte.d.ts
dev/storybook/package.json
dev/storybook/src/main.ts
dev/storybook/src/stories/Button_SB.stories.js
dev/storybook/src/stories/Header.stories.js
dev/storybook/src/stories/Page.stories.js
dev/storybook/src/stories/sparkling-controls/ActionBar.stories.js
dev/storybook/src/stories/sparkling-controls/Button.stories.js
dev/storybook/src/stories/sparkling-controls/CheckBox.stories.js
dev/storybook/src/stories/sparkling-controls/ComboBox.stories.js
dev/storybook/src/stories/sparkling-controls/EditBox.stories.js
dev/storybook/src/stories/sparkling-controls/InlineEdit.stories.js
dev/storybook/src/stories/sparkling-controls/ScrollView.stories.js
dev/storybook/src/stories/sparkling-controls/SplitView.stories.js
dev/storybook/src/stories/sparkling-controls/UserInfo.stories.js
dev/storybook/src/stories/sparkling-controls/menu/PopupItem.stories.js
dev/storybook/src/stories/sparkling-controls/menu/PopupMenu.stories.js
dev/storybook/src/stories/sparkling-controls/toolbar/Button.stories.js
dev/tool/package.json
dev/tool/src/index.ts
dev/tool/src/user.ts
packages/sparkling-controls/package.json
packages/sparkling-theme/package.json
packages/sparkling-theme/src/index.ts
packages/sparkling-theme/src/themes.ts

Add eslint to all projects: https://github.com/anticrm/platform/issues/261
Signed-off-by: Artyom Savchenko <armisav@gmail.com>

Add eslint to all projects and fix errors

---

plugins/platform-ui/src/plugin.ts

Fix router clear with undefined parent

Fix router clear with undefined parent

---

.vscode/settings.json
dev/boot/src/boot.ts
dev/boot/src/platform.ts
packages/model/src/index.ts
packages/sparkling-controls/src/EditBox.svelte
plugins/contact/src/__model__.ts
plugins/contact/src/index.ts
plugins/data-generator/src/components/internal/DataGeneratorView.svelte
plugins/person-extras/package.json
plugins/person-extras/src/__model__.ts
plugins/person-extras/src/components/ResumeEditor.svelte
plugins/person-extras/src/components/ResumeProps.svelte
plugins/person-extras/src/components/SkillEditor.svelte
plugins/person-extras/src/components/SkillsEditor.svelte
plugins/person-extras/src/components/StringListEditor.svelte
plugins/person-extras/src/index.ts
plugins/person-extras/src/plugin.ts
plugins/person-extras/tsconfig.json
plugins/recruiting/package.json
plugins/recruiting/src/__model__.ts
plugins/recruiting/src/components/Candidate.svelte
plugins/recruiting/src/components/CandidateList.svelte
plugins/recruiting/src/components/NewCandidate.svelte
plugins/recruiting/src/index.ts
plugins/recruiting/src/plugin.ts
plugins/recruiting/tsconfig.json
plugins/task/src/components/internal/NewTaskForm.svelte
plugins/workbench/src/components/internal/Application.svelte
plugins/workbench/src/components/internal/spaces/AddUser.svelte
plugins/workbench/src/components/internal/spaces/CreateSpace.svelte

Recruiting plugin

---

plugins/presentation/src/components/internal/Table.svelte

Table open action should use passed class

Table open action should use passed class

---

packages/sparkling-controls/src/calendar/MonthCalendar.svelte

Focus to selected date If it is specified. Fixes https://github.com/anticrm/platform/issues/332.
Add todayDate prop to use in it StoryBook: https://github.com/anticrm/platform/issues/334.
Signed-off-by: Artyom Savchenko <armisav@gmail.com>

Focus to selected date

---

packages/sparkling-controls/src/ComboBox.svelte
plugins/chunter/src/components/internal/ActivityView.svelte
plugins/chunter/src/components/internal/Comment.svelte
plugins/data-generator/src/components/internal/DataGeneratorView.svelte
plugins/login/src/components/LoginForm.svelte
plugins/login/src/components/SettingForm.svelte
plugins/platform-ui/src/components/ActionBar.svelte
plugins/platform-ui/src/components/ComboBox.svelte
plugins/platform-ui/src/components/UserBox.svelte
plugins/presentation/src/components/MessageViewer.svelte
plugins/presentation/src/components/internal/presenters/Presenter.svelte
plugins/presentation/src/components/internal/presenters/class/TablePresenter.svelte
plugins/presentation/src/components/internal/presenters/value/ArrayPresenter.svelte
plugins/presentation/src/components/internal/presenters/value/RefPresenter.svelte
plugins/presentation/src/components/refinput/CompletionPopupHelper.ts
plugins/presentation/src/components/refinput/ReferenceInput.svelte
plugins/task/src/components/internal/NewTaskForm.svelte
plugins/task/src/components/internal/TaskCardPresenter.svelte
plugins/task/src/components/internal/TaskProperties.svelte
plugins/task/src/components/internal/presenters/StatusPresenter.svelte
plugins/workbench/src/components/internal/ApplicationDashboard.svelte
plugins/workbench/src/components/internal/CreateForm.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte
plugins/workbench/src/components/internal/spaces/SpacePresenter.svelte

Fix warnings shown in Browser console.

Fix warnings in Browser Console.

---

package.json
packages/core/src/storage.ts
packages/domains/src/indices/filter.ts
packages/domains/src/indices/model.ts
packages/domains/src/indices/vdoc.ts
plugins/platform-core/src/operations.ts
plugins/platform-core/src/plugin.ts
server/server/src/workspace.ts

Modified and Created fields should be specified/updated on server and send to clients.
Closes #340 

Fix for #340

---

plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte

Fix issue #346 Broken link

---

packages/model/src/__model__.ts
packages/model/src/index.ts
packages/model/src/models/core.ts

Fix InstanceOf missing in model

---

packages/core/src/model.ts

Fix live query update for vacancies

Fix live query update for vacancies

---

plugins/platform-core/src/queries.ts

Fix Leave Space disappears on Leave
Issue was with remove live query processing.

Fix Leave Space disappears on Leave

---

dev/tool/src/index.ts

Fix for #365

---

packages/sparkling-controls/src/DateInput.svelte
packages/sparkling-controls/src/menu/PopupMenu.svelte
plugins/calendar/src/components/NewEventForm.svelte
plugins/platform-ui/src/components/internal/Modal.svelte

Fixes https://github.com/anticrm/platform/issues/381
Signed-off-by: Artyom Savchenko <armisav@gmail.com>

Fix date input popup position

---

packages/sparkling-controls/src/DateInput.svelte
packages/sparkling-controls/src/EditBox.svelte

Signed-off-by: Artyom Savchenko <armisav@gmail.com>

Fix date input according to new design

---

packages/core/src/model.ts

Mixin update should work as expected.

Fix Mixin update should work as expected.

---

plugins/platform-ui/src/components/internal/Root.svelte
plugins/platform-ui/src/index.ts
plugins/platform-ui/src/plugin.ts
plugins/platform-ui/src/routes.ts
plugins/presentation/src/components/MessageViewer.svelte
plugins/workbench/src/components/internal/DefaultPerspective.svelte

Fix for link navigation

---

v0.4/dev/storybook/src/stories/Button.stories.js
v0.4/dev/storybook/src/stories/EditBox.stories.js
v0.4/sparkling/controls/src/Button.svelte
v0.4/sparkling/controls/src/EditBox.svelte

fix EditBox merged label and placeholder

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte

design sign up panel

---

packages/core/src/classes.ts
packages/core/src/model.ts
packages/core/src/storage.ts
packages/domains/src/index.ts
packages/domains/src/indices/vdoc.ts
packages/model/src/__model__.ts
packages/model/src/index.ts
packages/model/src/models/tx.ts
plugins/activity/src/components/internal/ActivityItem.svelte
plugins/activity/src/components/internal/ActivityView.svelte
plugins/activity/src/components/internal/GenericInfo.svelte
plugins/activity/src/details.ts
plugins/platform-core/src/operations.ts
plugins/platform-core/src/tx.ts
plugins/recruiting/src/__model__.ts
plugins/task/src/components/internal/TaskInfo.svelte
plugins/workbench/src/components/internal/spaces/BrowseSpace.svelte
plugins/workbench/src/index.ts
server/server/src/__tests__/service.test.ts
server/server/src/mongo_utils.ts
server/server/src/service.ts
server/server/src/spaces.ts
server/server/src/workspace.ts

1. Closes #398 
2. Allow to search based on Base Class.

Transactions with _objectSpace

---

.vscode/settings.json
packages/core/package.json
packages/core/src/__tests__/model.test.ts
packages/core/src/__tests__/storage.test.ts
packages/core/src/__tests__/tasks.ts
packages/core/src/classes.ts
packages/core/src/model.ts
packages/core/src/storage.ts
packages/domains/src/index.ts
packages/model/src/index.ts
yarn.lock

Make package/core ts-standard compatible

Make package/core ts-standard compatible (part1)

---

.vscode/settings.json
packages/core/package.json
packages/core/src/__tests__/model.test.ts
packages/core/src/__tests__/storage.test.ts
packages/core/src/__tests__/tasks.ts
packages/core/src/classes.ts
packages/core/src/model.ts
packages/core/src/storage.ts
packages/domains/package.json
packages/domains/src/__tests__/model.test.ts
packages/domains/src/__tests__/title.index.test.ts
packages/domains/src/index.ts
packages/domains/src/indices/filter.ts
packages/domains/src/indices/model.ts
packages/domains/src/indices/reference.ts
packages/domains/src/indices/title.ts
packages/domains/src/indices/tx.ts
packages/domains/src/indices/vdoc.ts
packages/model/src/index.ts
yarn.lock

Domain ts standard
It depends on #418

Domain ts standard (part2)

---

packages/core/src/__tests__/model.test.ts
packages/core/src/__tests__/tasks.ts
packages/core/src/model.ts
packages/domains/src/index.ts
packages/model/src/index.ts
packages/rpc/package.json
plugins/platform-core/src/index.ts
server/server/babel.config.js
server/server/package.json
server/server/src/__tests__/mongo_util.test.ts
server/server/src/__tests__/server.test.ts
server/server/src/__tests__/serversuite.ts
server/server/src/index.ts
server/server/src/mongo_utils.ts
server/server/src/server.ts
server/server/src/serverctl.ts
server/server/src/service.ts
server/server/src/spaces.ts
server/server/src/workspace.ts

Server ts standard (part3)

---

packages/core/src/__tests__/model.test.ts
packages/core/src/__tests__/storage.test.ts
packages/core/src/__tests__/tasks.ts
packages/core/src/model.ts
packages/core/src/storage.ts
packages/domains/src/index.ts
packages/model/src/index.ts
packages/rpc/package.json
plugins/platform-core/package.json
plugins/platform-core/src/cache.ts
plugins/platform-core/src/clienttx.ts
plugins/platform-core/src/index.ts
plugins/platform-core/src/operations.ts
plugins/platform-core/src/plugin.ts
plugins/platform-core/src/queries.ts
plugins/platform-core/src/rpc.ts
plugins/platform-core/src/tx.ts
server/front/src/index.ts
server/server/babel.config.js
server/server/package.json
server/server/src/__tests__/mongo_util.test.ts
server/server/src/__tests__/server.test.ts
server/server/src/__tests__/serversuite.ts
server/server/src/index.ts
server/server/src/mongo_utils.ts
server/server/src/server.ts
server/server/src/serverctl.ts
server/server/src/service.ts
server/server/src/spaces.ts
server/server/src/workspace.ts

Platform core ts-standard enabled.

Platform core ts standard (part4)

---

plugins/task/src/__model__.ts

Fix TWorklog is missing

---

plugins/workbench/src/components/internal/DefaultPerspective.svelte

Fix for #431

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte

Changing the layout for normal scrolling

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte

Fix layout in registration form

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte
v0.4/plugins/ui-impl/src/components/Root.svelte

Change flex to grid

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte
v0.4/plugins/ui-impl/src/components/Root.svelte
v0.4/sparkling/controls/src/Panel.svelte
v0.4/sparkling/controls/src/index.ts
v0.4/sparkling/theme/styles/mixins.scss

Add panel component

---

v0.4/plugins/login-impl/src/components/LoginApp.svelte
v0.4/plugins/ui-impl/img/mute.svg
v0.4/plugins/ui-impl/img/wi-fi.svg
v0.4/plugins/ui-impl/src/components/Root.svelte
v0.4/plugins/ui-impl/src/components/ThemeSelector.svelte
v0.4/sparkling/theme/styles/global.scss

Redesign statusbar and hide scroll

---

v0.4/plugins/ui-impl/src/components/Root.svelte
v0.4/plugins/ui-impl/src/components/icons/Mute.svelte
v0.4/plugins/ui-impl/src/components/icons/WiFi.svelte

Fix widgets in status bar

---

server/server/src/server.ts
server/server/src/service.ts
server/server/src/workspace.ts

Browser should close workspace if there is no clients

Server should close workspace if there is no clients

---

packages/model/src/__model__.ts
packages/model/src/models/core.ts
plugins/presentation/src/__model__.ts

Add missing BagOf

---

server/accounts/src/index.ts
server/accounts/src/token.ts
server/server/src/__tests__/client.test.ts
server/server/src/__tests__/serversuite.ts

A example test of client to server operations

A example test of client to server operations

---

v0.4/plugins/login-impl/src/components/AppHeader.svelte

Fix link for EditBox

---

packages/core/src/model.ts
packages/model/src/__model__.ts
plugins/platform-core/src/plugin.ts
server/server/src/workspace.ts

Move spaces into model domain

---

v0.4/platform/platform/src/__tests__/i18n.test.ts

Signed-off-by: LoinASD <loinasd.dev@gmail.com>

i18n error tests

---

v0.4/platform/core/src/__tests__/model.test.ts
v0.4/platform/core/src/__tests__/storage.test.ts
v0.4/platform/core/src/classes.ts
v0.4/platform/core/src/model.ts
v0.4/platform/core/src/storage.ts
v0.4/platform/domains/src/__tests__/model.test.ts
v0.4/platform/domains/src/__tests__/title.index.test.ts
v0.4/platform/domains/src/index.ts
v0.4/platform/domains/src/tx/clienttx.ts
v0.4/platform/domains/src/tx/modeltx.ts
v0.4/platform/domains/src/tx/operations.ts
v0.4/platform/domains/src/tx/tx.ts

Remove Property From core, domain

---

v0.4/common/scripts/install-run.js
v0.4/rush.json

Rush update v5.46.1

---

v0.4/platform/platform/src/__tests__/i18n.test.ts

Signed-off-by: LoinASD <loinasd.dev@gmail.com>

add verification for translate, remove useless tests

---

v0.4/platform/core/src/__tests__/model.test.ts
v0.4/platform/core/src/classes.ts
v0.4/platform/core/src/ids.ts
v0.4/platform/core/src/index.ts
v0.4/platform/core/src/model.ts
v0.4/platform/core/src/storage.ts
v0.4/platform/domains/src/__tests__/model.test.ts
v0.4/platform/domains/src/index.ts
v0.4/platform/domains/src/indices/title.ts
v0.4/platform/domains/src/primary.ts
v0.4/platform/domains/src/tx/operations.ts

Move Indexes and Primary index into domain
Closes #490

Move Indexes and Primary index into domain Closes #490

---

v0.4/common/config/rush/pnpm-lock.yaml
v0.4/platform/core/package.json
v0.4/platform/core/src/__tests__/model.test.ts
v0.4/platform/core/src/__tests__/search.test.ts
v0.4/platform/core/src/__tests__/storage.test.ts
v0.4/platform/core/src/__tests__/tasks.ts
v0.4/platform/core/src/model.ts
v0.4/platform/domains/src/index.ts
v0.4/platform/model/src/index.ts
v0.4/platform/model/src/models/core.ts

1. Fix find method to work with mixins.
2. Move mongo query methods out from model, they are not really used.
PR should be applied after #506

Fix find move query stuff

---

v0.4/platform/core/src/storage.ts
v0.4/platform/domains/src/index.ts
v0.4/platform/domains/src/tx/operations.ts
v0.4/platform/storage-mongo/.eslintrc.js
v0.4/platform/storage-mongo/api-extractor.json
v0.4/platform/storage-mongo/jest.config.js
v0.4/platform/storage-mongo/package.json
v0.4/platform/storage-mongo/src/__tests__/storage.test.ts
v0.4/platform/storage-mongo/src/index.ts
v0.4/platform/storage-mongo/src/query.ts
v0.4/platform/storage-mongo/src/storage.ts
v0.4/platform/storage-mongo/tsconfig.json
v0.4/rush.json

Define a Storage to be used for MongoDB + tests

Define a Storage to be used for MongoDB
